# Generated by Django 5.1.6 on 2025-03-06 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='own_city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cities.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.RemoveField(
            model_name='user',
            name='city_preference',
        ),
        migrations.AddField(
            model_name='user',
            name='city_preference',
            field=models.ManyToManyField(default=0, related_name='preferred_by_users', to='cities.city'),
        ),
    ]
