# Generated by Django 5.1.6 on 2025-03-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_own_city_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city_preference',
        ),
    ]
