# Generated by Django 5.1.6 on 2025-03-06 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_city_id_alter_city_city_name'),
        ('users', '0003_remove_user_city_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='own_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.city'),
        ),
    ]
