# Generated by Django 5.1.6 on 2025-02-22 09:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_hall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='hall_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
