# Generated by Django 5.1.7 on 2025-03-19 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_hall', '0002_alter_hall_hall_id'),
        ('cities', '0002_alter_city_city_id_alter_city_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='hall_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city'),
        ),
    ]
