# Generated by Django 5.1.6 on 2025-03-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False, unique=True)),
                ('city_name', models.CharField(max_length=250)),
            ],
        ),
    ]
