# Generated by Django 5.1.6 on 2025-02-23 06:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=250)),
                ('movie_genres', models.CharField(max_length=300)),
                ('story', models.TextField()),
                ('lead_actors', models.JSONField(default=list)),
            ],
        ),
    ]
