# Generated by Django 5.1.6 on 2025-03-06 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema_hall', '0002_alter_hall_hall_id'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_price', models.DecimalField(decimal_places=0, max_digits=3)),
                ('show_time', models.DateTimeField()),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('cinema_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_hall.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
